"""codec

Revision ID: 69a30a0afb72
Revises: d2cb3f84f349
Create Date: 2025-10-08 22:35:05.832346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "69a30a0afb72"
down_revision: Union[str, Sequence[str], None] = "d2cb3f84f349"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incomingpeeringrequest",
        sa.Column("codec", sa.String(16), nullable=False, server_default="g722"),
    )
    op.add_column(
        "outgoingpeeringrequest",
        sa.Column("codec", sa.String(16), nullable=False, server_default="g722"),
    )
    op.add_column(
        "peer", sa.Column("codec", sa.String(16), nullable=False, server_default="g722")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("peer", "codec")
    op.drop_column("outgoingpeeringrequest", "codec")
    op.drop_column("incomingpeeringrequest", "codec")
    # ### end Alembic commands ###
