name: uURU CI

on:
  - push
  - workflow_dispatch

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            include:
                - Dockerfile: ./Dockerfile
                  image: olel/uuru:latest
                  context: ./
                - Dockerfile: ./asterisk/Dockerfile
                  image: olel/uuru-asterisk:latest
                  context: ./asterisk/

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: olel
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.Dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.image }}
            