name: uURU CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
            include:
                - Dockerfile: ./Dockerfile
                  image: olel/uuru:PR-${{ github.event.number }}
                  context: ./
                - Dockerfile: ./asterisk/Dockerfile
                  image: olel/uuru-asterisk:PR-${{ github.event.number }}
                  context: ./asterisk/
    
    if: !contains(github.event.pull_request.title, 'SMALL') && !contains(github.event.pull_request.title, 'WIP')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: olel
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.Dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.image }}
            